Formatting awk programs

diff --git a/pkgnew b/pkgnew
--- a/pkgnew
+++ b/pkgnew
@@ -147,15 +147,16 @@ PortsOrder() {
 		delete Val[n]
 		return 1
 	}
-	/^$/	{ exit 2 }
-	/^ /	{ Err($0); next }
-	/^Bad/	{ Bad[$2] = ""; next }
-	/^Dep/	{ Dep[n] = substr($0, 4); next }
-	/^Pkg/	{ Pkg[n] = substr($0, 4); next }
-	/^Run/	{ Pkg[n] = Pkg[n] " +"; next }
-	/^Who/	{ Who[n] = substr($0, 4); next }
+	/^$/ { exit 2 }
+	/^ / { Err($0); next }
+	/^Bad/ { Bad[$2] = ""; next }
+	/^Dep/ { Dep[n] = substr($0, 4); next }
+	/^Pkg/ { Pkg[n] = substr($0, 4); next }
+	/^Run/ { Pkg[n] = Pkg[n] " +"; next }
+	/^Who/ { Who[n] = substr($0, 4); next }
 	{ Ord[++i] = n = $1; Val[n] = $2 " " $3; sub(/^.+=/,""); Src[n] = $0 }
-	END {	if(E) exit 1
+	END {
+		if(E) exit 1
 		for(n in Val) {
 			delete s
 			split(Dep[n], a)
@@ -165,7 +166,8 @@ PortsOrder() {
 				for(i in Val) s[i] = i
 			}
 			delete s[n]
-			do {	l = ""
+			do {
+				l = ""
 				for(j in s) {
 					if(j in Bad) Bad[j] = Bad[j] " " n
 					delete u
@@ -194,7 +196,8 @@ PortsOrder() {
 		}
 		if(E) exit 1
 		asort(Ord)
-		do {	n = 0
+		do {
+			n = 0
 			for(i in Ord) if(Out(Ord[i])) delete Ord[n = i]
 		} while(n)
 		if(asort(Ord)) {
@@ -309,7 +312,7 @@ CreatePackages() { # Pkg ...
 	local P
 	for P do
 		( cd $P && /usr/bin/bsdtar -caf ../$P#$VER$EXT *) ||
-			 End Failed to create package $P#$VER$EXT!
+			End Failed to create package $P#$VER$EXT!
 	done
 	/bin/mv *#$VER$EXT $PKG_DIR
 }
@@ -435,7 +438,7 @@ CheckPkgFiles() { # Pkg
 		*[Pp]ython*) echo /usr/bin/python
 		esac
 	done | /usr/bin/awk '{ if($0 ~ /^\//) U[$1] = $1; else L[$1] = $1 }
-		END{ asort(U); for(n in U) { n = U[n]; if(!(n in L)) print n }}'
+		END { asort(U); for(n in U) if(!(U[n] in L)) print U[n] }'
 }
 CreateUse() {
 	/usr/bin/awk '
@@ -446,46 +449,46 @@ CreateUse() {
 	}
 	function All(n) { Dep["ALL"] = Dep["ALL"] " " n }
 	function Out(n) {
-			if(n in Who) print Who[n]
-			print n "#" Val[n] Dep[n]
-			if(n in Run) print Run[n]
-			delete Val[n]
-		}
+		if(n in Who) print Who[n]
+		print n "#" Val[n] Dep[n]
+		if(n in Run) print Run[n]
+		delete Val[n]
+	}
 	function Err(s) { E++; print "\t  " s >"/dev/stderr" }
 	function Str(u) {
-			n = $1; u["filesystem"] = 0
-			for(i = 1; ++i <= NF;) {
-				if($i in Val) u[$i] = 0
-				else if(Lib[$i]) u[Lib[$i]] = 0
-				else if($i ~ /\//) Use[$i] = Use[$i] " " n
-				else Pkg[$i] = Pkg[$i] " " n
-			}
-			delete u[n]
-			for(i in u) { Dep[n] = Dep[n] " " i; Req[i]++ }
+		n = $1; u["filesystem"] = 0
+		for(i = 1; i++ < NF;) {
+			if($i in Val) u[$i] = 0
+			else if(Lib[$i]) u[Lib[$i]] = 0
+			else if($i ~ /\//) Use[$i] = Use[$i] " " n
+			else Pkg[$i] = Pkg[$i] " " n
 		}
-	/^\//	{ Lib[$1] = n; next }
-	/^=/	{ Val[Ord[++c] = n = $2] = $3; All(n); next }
-	/^Pkg/	{
-			if(/ \+ /) Run[$4] = "+ " $4
-			f = $2 "/" $4 "/.pkguse"
-			while(g = getline < f) {
-				if(g == -1) { Err("Missing file " f); break }
-				Str()
-			}
-			next
+		delete u[n]
+		for(i in u) { Dep[n] = Dep[n] " " i; Req[i]++ }
+	}
+	/^\// {	Lib[$1] = n; next }
+	/^=/ { Val[Ord[++c] = n = $2] = $3; All(n); next }
+	/^Pkg/ {
+		if(/ \+ /) Run[$4] = "+ " $4
+		f = $2 "/" $4 "/.pkguse"
+		while(g = getline < f) {
+			if(g == -1) { Err("Missing file " f); break }
+			Str()
 		}
-	/^Who/	{ $1 = "@"; Who[$2] = $0; next }
+		next
+	}
+	/^Who/ { $1 = "@"; Who[$2] = $0; next }
 	/^[A-Z]/ { Val[Ord[++c] = $1] = "0"; Str(); next }
-		{
-			delete u
-			for(n = 1; ++n <= NF;) if($n in Val) u[$n] = $n
-			asort(u)
-			l = ""
-			for(n in u) l = l " " u[n]
-			Val[Ord[++c] = n = toupper($1)] = "0"
-			Grp[n] = Dep[n] = l
-			All(n)
-		}
+	{
+		delete u
+		for(n = 1; n++ < NF;) if($n in Val) u[$n] = $n
+		asort(u)
+		l = ""
+		for(n in u) l = l " " u[n]
+		Val[Ord[++c] = n = toupper($1)] = "0"
+		Grp[n] = Dep[n] = l
+		All(n)
+	}
 	END {
 		delete Lib
 		for(n in Pkg) Err("missing package " n " required by" Pkg[n])
@@ -495,7 +498,8 @@ CreateUse() {
 			delete s
 			split(Dep[n], a)
 			for(i in a) s[a[i]] = a[i]
-			do {	l = ""
+			do {
+				l = ""
 				for(j in s) {
 					delete u
 					u[n] = l = j
@@ -518,7 +522,8 @@ CreateUse() {
 			Dep[n] = l
 		}
 		for(n in Grp) Dep[n] = Grp[n]
-		do {	j = 0
+		do {
+			j = 0
 			for(n in Ord) if(Ord[n] in Val) {
 				split(Dep[n = Ord[n]], a)
 				for(i in a) if(a[i] in Val) { n = 0; break }
@@ -706,12 +711,12 @@ DeleteUnused() {
 	case $CMD in ''|*z*);; *) return 0;; esac
 	echo ${PKGMK_SOURCE_DIR:+$PKGMK_SOURCE_DIR/*} \
 		${PKGMK_PACKAGE_DIR:+$PKGMK_PACKAGE_DIR/*#*} | /usr/bin/awk '
-	BEGIN	{
+	BEGIN {
 		E = "'$EXT'"
 		P = "'$PKGMK_PACKAGE_DIR'"
 		S = "'$PKGMK_SOURCE_DIR'"
-		}
-	/^Pkg/  {
+	}
+	/^Pkg/ {
 		for(i = 3; i++ < NF;) {
 			if($i == "=") break
 			if($i != "+") p = $i "#" $3 E
@@ -723,8 +728,8 @@ DeleteUnused() {
 			if(sub(/^.+\//, "", $i) && S) F[S "/" $i] = 0
 		}
 		next
-		}
-	/\//	{
+	}
+	/\// {
 		for(i = 0; i++ < NF;)
 			if(!($i in F || $i ~ /*/)) print "RmCmd " $i
 	}' $TMP/PKG.new - >$TMP/Del
